package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CITY".
 */
@Entity
public class City {

    @NotNull
    private String pro_id;

    @NotNull
    private String pro_code;

    @NotNull
    private String cit_code;

    @NotNull
    private String pro_province;

    @NotNull
    private String pro_city;

    @Generated(hash = 750791287)
    public City() {
    }

    @Generated(hash = 1754687909)
    public City(@NotNull String pro_id, @NotNull String pro_code, @NotNull String cit_code,
            @NotNull String pro_province, @NotNull String pro_city) {
        this.pro_id = pro_id;
        this.pro_code = pro_code;
        this.cit_code = cit_code;
        this.pro_province = pro_province;
        this.pro_city = pro_city;
    }

    @NotNull
    public String getPro_id() {
        return pro_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_id(@NotNull String pro_id) {
        this.pro_id = pro_id;
    }

    @NotNull
    public String getPro_code() {
        return pro_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_code(@NotNull String pro_code) {
        this.pro_code = pro_code;
    }

    @NotNull
    public String getCit_code() {
        return cit_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCit_code(@NotNull String cit_code) {
        this.cit_code = cit_code;
    }

    @NotNull
    public String getPro_province() {
        return pro_province;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_province(@NotNull String pro_province) {
        this.pro_province = pro_province;
    }

    @NotNull
    public String getPro_city() {
        return pro_city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_city(@NotNull String pro_city) {
        this.pro_city = pro_city;
    }

}
