package com.karyastudio.izn.dao.generateSchema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.karyastudio.izn.dao.generateSchema.City;
import com.karyastudio.izn.dao.generateSchema.IZN;
import com.karyastudio.izn.dao.generateSchema.KDZ;
import com.karyastudio.izn.dao.generateSchema.Kdzformqueue;
import com.karyastudio.izn.dao.generateSchema.KDZQueue;
import com.karyastudio.izn.dao.generateSchema.Keluarga;
import com.karyastudio.izn.dao.generateSchema.KeluargaQueue;
import com.karyastudio.izn.dao.generateSchema.Petugas;
import com.karyastudio.izn.dao.generateSchema.Province;
import com.karyastudio.izn.dao.generateSchema.Provinsi;

import com.karyastudio.izn.dao.generateSchema.CityDao;
import com.karyastudio.izn.dao.generateSchema.IZNDao;
import com.karyastudio.izn.dao.generateSchema.KDZDao;
import com.karyastudio.izn.dao.generateSchema.KdzformqueueDao;
import com.karyastudio.izn.dao.generateSchema.KDZQueueDao;
import com.karyastudio.izn.dao.generateSchema.KeluargaDao;
import com.karyastudio.izn.dao.generateSchema.KeluargaQueueDao;
import com.karyastudio.izn.dao.generateSchema.PetugasDao;
import com.karyastudio.izn.dao.generateSchema.ProvinceDao;
import com.karyastudio.izn.dao.generateSchema.ProvinsiDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig iZNDaoConfig;
    private final DaoConfig kDZDaoConfig;
    private final DaoConfig kdzformqueueDaoConfig;
    private final DaoConfig kDZQueueDaoConfig;
    private final DaoConfig keluargaDaoConfig;
    private final DaoConfig keluargaQueueDaoConfig;
    private final DaoConfig petugasDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig provinsiDaoConfig;

    private final CityDao cityDao;
    private final IZNDao iZNDao;
    private final KDZDao kDZDao;
    private final KdzformqueueDao kdzformqueueDao;
    private final KDZQueueDao kDZQueueDao;
    private final KeluargaDao keluargaDao;
    private final KeluargaQueueDao keluargaQueueDao;
    private final PetugasDao petugasDao;
    private final ProvinceDao provinceDao;
    private final ProvinsiDao provinsiDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        iZNDaoConfig = daoConfigMap.get(IZNDao.class).clone();
        iZNDaoConfig.initIdentityScope(type);

        kDZDaoConfig = daoConfigMap.get(KDZDao.class).clone();
        kDZDaoConfig.initIdentityScope(type);

        kdzformqueueDaoConfig = daoConfigMap.get(KdzformqueueDao.class).clone();
        kdzformqueueDaoConfig.initIdentityScope(type);

        kDZQueueDaoConfig = daoConfigMap.get(KDZQueueDao.class).clone();
        kDZQueueDaoConfig.initIdentityScope(type);

        keluargaDaoConfig = daoConfigMap.get(KeluargaDao.class).clone();
        keluargaDaoConfig.initIdentityScope(type);

        keluargaQueueDaoConfig = daoConfigMap.get(KeluargaQueueDao.class).clone();
        keluargaQueueDaoConfig.initIdentityScope(type);

        petugasDaoConfig = daoConfigMap.get(PetugasDao.class).clone();
        petugasDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        provinsiDaoConfig = daoConfigMap.get(ProvinsiDao.class).clone();
        provinsiDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        iZNDao = new IZNDao(iZNDaoConfig, this);
        kDZDao = new KDZDao(kDZDaoConfig, this);
        kdzformqueueDao = new KdzformqueueDao(kdzformqueueDaoConfig, this);
        kDZQueueDao = new KDZQueueDao(kDZQueueDaoConfig, this);
        keluargaDao = new KeluargaDao(keluargaDaoConfig, this);
        keluargaQueueDao = new KeluargaQueueDao(keluargaQueueDaoConfig, this);
        petugasDao = new PetugasDao(petugasDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        provinsiDao = new ProvinsiDao(provinsiDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(IZN.class, iZNDao);
        registerDao(KDZ.class, kDZDao);
        registerDao(Kdzformqueue.class, kdzformqueueDao);
        registerDao(KDZQueue.class, kDZQueueDao);
        registerDao(Keluarga.class, keluargaDao);
        registerDao(KeluargaQueue.class, keluargaQueueDao);
        registerDao(Petugas.class, petugasDao);
        registerDao(Province.class, provinceDao);
        registerDao(Provinsi.class, provinsiDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        iZNDaoConfig.clearIdentityScope();
        kDZDaoConfig.clearIdentityScope();
        kdzformqueueDaoConfig.clearIdentityScope();
        kDZQueueDaoConfig.clearIdentityScope();
        keluargaDaoConfig.clearIdentityScope();
        keluargaQueueDaoConfig.clearIdentityScope();
        petugasDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
        provinsiDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public IZNDao getIZNDao() {
        return iZNDao;
    }

    public KDZDao getKDZDao() {
        return kDZDao;
    }

    public KdzformqueueDao getKdzformqueueDao() {
        return kdzformqueueDao;
    }

    public KDZQueueDao getKDZQueueDao() {
        return kDZQueueDao;
    }

    public KeluargaDao getKeluargaDao() {
        return keluargaDao;
    }

    public KeluargaQueueDao getKeluargaQueueDao() {
        return keluargaQueueDao;
    }

    public PetugasDao getPetugasDao() {
        return petugasDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public ProvinsiDao getProvinsiDao() {
        return provinsiDao;
    }

}
