package com.karyastudio.izn.dao.generateSchema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.karyastudio.izn.dao.generateSchema.IZN;
import com.karyastudio.izn.dao.generateSchema.Keluarga;
import com.karyastudio.izn.dao.generateSchema.Provinsi;
import com.karyastudio.izn.dao.generateSchema.KDZ;
import com.karyastudio.izn.dao.generateSchema.Province;
import com.karyastudio.izn.dao.generateSchema.City;
import com.karyastudio.izn.dao.generateSchema.Petugas;

import com.karyastudio.izn.dao.generateSchema.IZNDao;
import com.karyastudio.izn.dao.generateSchema.KeluargaDao;
import com.karyastudio.izn.dao.generateSchema.ProvinsiDao;
import com.karyastudio.izn.dao.generateSchema.KDZDao;
import com.karyastudio.izn.dao.generateSchema.ProvinceDao;
import com.karyastudio.izn.dao.generateSchema.CityDao;
import com.karyastudio.izn.dao.generateSchema.PetugasDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iZNDaoConfig;
    private final DaoConfig keluargaDaoConfig;
    private final DaoConfig provinsiDaoConfig;
    private final DaoConfig kDZDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig petugasDaoConfig;

    private final IZNDao iZNDao;
    private final KeluargaDao keluargaDao;
    private final ProvinsiDao provinsiDao;
    private final KDZDao kDZDao;
    private final ProvinceDao provinceDao;
    private final CityDao cityDao;
    private final PetugasDao petugasDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iZNDaoConfig = daoConfigMap.get(IZNDao.class).clone();
        iZNDaoConfig.initIdentityScope(type);

        keluargaDaoConfig = daoConfigMap.get(KeluargaDao.class).clone();
        keluargaDaoConfig.initIdentityScope(type);

        provinsiDaoConfig = daoConfigMap.get(ProvinsiDao.class).clone();
        provinsiDaoConfig.initIdentityScope(type);

        kDZDaoConfig = daoConfigMap.get(KDZDao.class).clone();
        kDZDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        petugasDaoConfig = daoConfigMap.get(PetugasDao.class).clone();
        petugasDaoConfig.initIdentityScope(type);

        iZNDao = new IZNDao(iZNDaoConfig, this);
        keluargaDao = new KeluargaDao(keluargaDaoConfig, this);
        provinsiDao = new ProvinsiDao(provinsiDaoConfig, this);
        kDZDao = new KDZDao(kDZDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        petugasDao = new PetugasDao(petugasDaoConfig, this);

        registerDao(IZN.class, iZNDao);
        registerDao(Keluarga.class, keluargaDao);
        registerDao(Provinsi.class, provinsiDao);
        registerDao(KDZ.class, kDZDao);
        registerDao(Province.class, provinceDao);
        registerDao(City.class, cityDao);
        registerDao(Petugas.class, petugasDao);
    }
    
    public void clear() {
        iZNDaoConfig.clearIdentityScope();
        keluargaDaoConfig.clearIdentityScope();
        provinsiDaoConfig.clearIdentityScope();
        kDZDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
        cityDaoConfig.clearIdentityScope();
        petugasDaoConfig.clearIdentityScope();
    }

    public IZNDao getIZNDao() {
        return iZNDao;
    }

    public KeluargaDao getKeluargaDao() {
        return keluargaDao;
    }

    public ProvinsiDao getProvinsiDao() {
        return provinsiDao;
    }

    public KDZDao getKDZDao() {
        return kDZDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public PetugasDao getPetugasDao() {
        return petugasDao;
    }

}
