package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IZN".
 */
@Entity
public class IZN {

    @NotNull
    private String fi_id;

    @NotNull
    private String fi_code;

    @NotNull
    private String fi_date_created;

    @NotNull
    private String fi_date_updated;

    @NotNull
    private String fi_jenis_lembaga;

    @Generated(hash = 996756118)
    public IZN() {
    }

    @Generated(hash = 1141668620)
    public IZN(@NotNull String fi_id, @NotNull String fi_code, @NotNull String fi_date_created,
            @NotNull String fi_date_updated, @NotNull String fi_jenis_lembaga) {
        this.fi_id = fi_id;
        this.fi_code = fi_code;
        this.fi_date_created = fi_date_created;
        this.fi_date_updated = fi_date_updated;
        this.fi_jenis_lembaga = fi_jenis_lembaga;
    }

    @NotNull
    public String getFi_id() {
        return fi_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFi_id(@NotNull String fi_id) {
        this.fi_id = fi_id;
    }

    @NotNull
    public String getFi_code() {
        return fi_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFi_code(@NotNull String fi_code) {
        this.fi_code = fi_code;
    }

    @NotNull
    public String getFi_date_created() {
        return fi_date_created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFi_date_created(@NotNull String fi_date_created) {
        this.fi_date_created = fi_date_created;
    }

    @NotNull
    public String getFi_date_updated() {
        return fi_date_updated;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFi_date_updated(@NotNull String fi_date_updated) {
        this.fi_date_updated = fi_date_updated;
    }

    @NotNull
    public String getFi_jenis_lembaga() {
        return fi_jenis_lembaga;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFi_jenis_lembaga(@NotNull String fi_jenis_lembaga) {
        this.fi_jenis_lembaga = fi_jenis_lembaga;
    }

}
