package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "KDZ".
 */
@Entity
public class KDZ {

    @Id
    @NotNull
    private String fk_id;

    @NotNull
    private String fk_date_created;

    @NotNull
    private String fk_date_updated;

    @NotNull
    private String fk_nama;

    @NotNull
    private String countKeluarga;

    @Generated(hash = 763870821)
    public KDZ() {
    }

    public KDZ(String fk_id) {
        this.fk_id = fk_id;
    }

    @Generated(hash = 837041414)
    public KDZ(@NotNull String fk_id, @NotNull String fk_date_created, @NotNull String fk_date_updated,
            @NotNull String fk_nama, @NotNull String countKeluarga) {
        this.fk_id = fk_id;
        this.fk_date_created = fk_date_created;
        this.fk_date_updated = fk_date_updated;
        this.fk_nama = fk_nama;
        this.countKeluarga = countKeluarga;
    }

    @NotNull
    public String getFk_id() {
        return fk_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_id(@NotNull String fk_id) {
        this.fk_id = fk_id;
    }

    @NotNull
    public String getFk_date_created() {
        return fk_date_created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_date_created(@NotNull String fk_date_created) {
        this.fk_date_created = fk_date_created;
    }

    @NotNull
    public String getFk_date_updated() {
        return fk_date_updated;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_date_updated(@NotNull String fk_date_updated) {
        this.fk_date_updated = fk_date_updated;
    }

    @NotNull
    public String getFk_nama() {
        return fk_nama;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_nama(@NotNull String fk_nama) {
        this.fk_nama = fk_nama;
    }

    @NotNull
    public String getCountKeluarga() {
        return countKeluarga;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCountKeluarga(@NotNull String countKeluarga) {
        this.countKeluarga = countKeluarga;
    }

}
