package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "KDZFORMQUEUE".
 */
@Entity
public class Kdzformqueue {

    @NotNull
    private String status;

    @NotNull
    private String request_type;

    @Id
    @NotNull
    private String fk_id;

    @NotNull
    private String UID;

    @NotNull
    private String M1_created_at;

    @NotNull
    private String M1_updated_at;

    @NotNull
    private String M1_nama;

    @NotNull
    private String M1_101;

    @NotNull
    private String M1_102;

    @NotNull
    private String M1_103;

    @NotNull
    private String M1_104;

    @NotNull
    private String M1_105;

    @NotNull
    private String M1_106;

    @NotNull
    private String M1_107;

    @NotNull
    private String M1_108;

    @NotNull
    private String M1_109;

    @NotNull
    private String M1_110;

    @NotNull
    private String M1_401;

    @NotNull
    private String M1_402;

    @NotNull
    private String M1_403;

    @NotNull
    private String M1_404;

    @NotNull
    private String M1_405;

    @NotNull
    private String M1_406;

    @NotNull
    private String M1_407;

    @NotNull
    private String M1_501;

    @NotNull
    private String M1_502;

    @NotNull
    private String M1_503;

    @NotNull
    private String M1_504;

    @NotNull
    private String M1_505;

    @NotNull
    private String M1_506;

    @NotNull
    private String M1_507;

    @NotNull
    private String M1_508;

    @NotNull
    private String M1_509;

    @NotNull
    private String M1_510;

    @NotNull
    private String M1_601;

    @NotNull
    private String M1_601_kode;

    @NotNull
    private String M1_602_kode;

    @NotNull
    private String M1_603_kode;

    @NotNull
    private String M1_602;

    @NotNull
    private String M1_603;

    @NotNull
    private String M1_604;

    @NotNull
    private String M1_605;

    @NotNull
    private String M1_606;

    @NotNull
    private String M1_607;

    @NotNull
    private String M1_608;

    @NotNull
    private String M1_609;

    @NotNull
    private String M1_610;

    @NotNull
    private String M1_611;

    @NotNull
    private String M1_612;

    @NotNull
    private String M1_613;

    @NotNull
    private String M1_614;

    @NotNull
    private String M1_615;

    @NotNull
    private String M1_616;

    @NotNull
    private String M1_617;

    @NotNull
    private String M1_618;

    @NotNull
    private String M1_701;

    @NotNull
    private String M1_702;

    @NotNull
    private String M1_703;

    @NotNull
    private String M1_801;

    @NotNull
    private String M1_802;

    @NotNull
    private String M1_803;

    @NotNull
    private String M1_804;

    @NotNull
    private String M1_805;

    @NotNull
    private String M1_806;

    @NotNull
    private String M1_807;

    @NotNull
    private String M1_808;

    @NotNull
    private String M1_809;

    @NotNull
    private String M1_810;

    @NotNull
    private String M1_811;

    @NotNull
    private String M1_812;

    @NotNull
    private String M1_813;

    @NotNull
    private String M1_814;

    @NotNull
    private String M1_815;

    @NotNull
    private String M1_lik1;

    @NotNull
    private String M1_lik2;

    @NotNull
    private String M1_lik3;

    @NotNull
    private String M1_lik4;

    @NotNull
    private String M1_lik5;

    @NotNull
    private String M1_lik1B;

    @NotNull
    private String M1_lik2B;

    @NotNull
    private String M1_lik3B;

    @NotNull
    private String M1_lik4B;

    @NotNull
    private String M1_lik5B;

    @Generated(hash = 1398777077)
    public Kdzformqueue() {
    }

    public Kdzformqueue(String fk_id) {
        this.fk_id = fk_id;
    }

    @Generated(hash = 1254543328)
    public Kdzformqueue(@NotNull String status, @NotNull String request_type, @NotNull String fk_id, @NotNull String UID, @NotNull String M1_created_at, @NotNull String M1_updated_at, @NotNull String M1_nama, @NotNull String M1_101, @NotNull String M1_102, @NotNull String M1_103, @NotNull String M1_104, @NotNull String M1_105, @NotNull String M1_106, @NotNull String M1_107, @NotNull String M1_108, @NotNull String M1_109, @NotNull String M1_110, @NotNull String M1_401, @NotNull String M1_402, @NotNull String M1_403, @NotNull String M1_404, @NotNull String M1_405, @NotNull String M1_406, @NotNull String M1_407, @NotNull String M1_501, @NotNull String M1_502, @NotNull String M1_503, @NotNull String M1_504, @NotNull String M1_505, @NotNull String M1_506, @NotNull String M1_507, @NotNull String M1_508, @NotNull String M1_509, @NotNull String M1_510, @NotNull String M1_601, @NotNull String M1_601_kode, @NotNull String M1_602_kode, @NotNull String M1_603_kode, @NotNull String M1_602, @NotNull String M1_603, @NotNull String M1_604, @NotNull String M1_605, @NotNull String M1_606, @NotNull String M1_607, @NotNull String M1_608, @NotNull String M1_609, @NotNull String M1_610, @NotNull String M1_611, @NotNull String M1_612, @NotNull String M1_613, @NotNull String M1_614, @NotNull String M1_615,
            @NotNull String M1_616, @NotNull String M1_617, @NotNull String M1_618, @NotNull String M1_701, @NotNull String M1_702, @NotNull String M1_703, @NotNull String M1_801, @NotNull String M1_802, @NotNull String M1_803, @NotNull String M1_804, @NotNull String M1_805, @NotNull String M1_806, @NotNull String M1_807, @NotNull String M1_808, @NotNull String M1_809, @NotNull String M1_810, @NotNull String M1_811, @NotNull String M1_812, @NotNull String M1_813, @NotNull String M1_814, @NotNull String M1_815, @NotNull String M1_lik1, @NotNull String M1_lik2, @NotNull String M1_lik3, @NotNull String M1_lik4, @NotNull String M1_lik5, @NotNull String M1_lik1B, @NotNull String M1_lik2B, @NotNull String M1_lik3B, @NotNull String M1_lik4B, @NotNull String M1_lik5B) {
        this.status = status;
        this.request_type = request_type;
        this.fk_id = fk_id;
        this.UID = UID;
        this.M1_created_at = M1_created_at;
        this.M1_updated_at = M1_updated_at;
        this.M1_nama = M1_nama;
        this.M1_101 = M1_101;
        this.M1_102 = M1_102;
        this.M1_103 = M1_103;
        this.M1_104 = M1_104;
        this.M1_105 = M1_105;
        this.M1_106 = M1_106;
        this.M1_107 = M1_107;
        this.M1_108 = M1_108;
        this.M1_109 = M1_109;
        this.M1_110 = M1_110;
        this.M1_401 = M1_401;
        this.M1_402 = M1_402;
        this.M1_403 = M1_403;
        this.M1_404 = M1_404;
        this.M1_405 = M1_405;
        this.M1_406 = M1_406;
        this.M1_407 = M1_407;
        this.M1_501 = M1_501;
        this.M1_502 = M1_502;
        this.M1_503 = M1_503;
        this.M1_504 = M1_504;
        this.M1_505 = M1_505;
        this.M1_506 = M1_506;
        this.M1_507 = M1_507;
        this.M1_508 = M1_508;
        this.M1_509 = M1_509;
        this.M1_510 = M1_510;
        this.M1_601 = M1_601;
        this.M1_601_kode = M1_601_kode;
        this.M1_602_kode = M1_602_kode;
        this.M1_603_kode = M1_603_kode;
        this.M1_602 = M1_602;
        this.M1_603 = M1_603;
        this.M1_604 = M1_604;
        this.M1_605 = M1_605;
        this.M1_606 = M1_606;
        this.M1_607 = M1_607;
        this.M1_608 = M1_608;
        this.M1_609 = M1_609;
        this.M1_610 = M1_610;
        this.M1_611 = M1_611;
        this.M1_612 = M1_612;
        this.M1_613 = M1_613;
        this.M1_614 = M1_614;
        this.M1_615 = M1_615;
        this.M1_616 = M1_616;
        this.M1_617 = M1_617;
        this.M1_618 = M1_618;
        this.M1_701 = M1_701;
        this.M1_702 = M1_702;
        this.M1_703 = M1_703;
        this.M1_801 = M1_801;
        this.M1_802 = M1_802;
        this.M1_803 = M1_803;
        this.M1_804 = M1_804;
        this.M1_805 = M1_805;
        this.M1_806 = M1_806;
        this.M1_807 = M1_807;
        this.M1_808 = M1_808;
        this.M1_809 = M1_809;
        this.M1_810 = M1_810;
        this.M1_811 = M1_811;
        this.M1_812 = M1_812;
        this.M1_813 = M1_813;
        this.M1_814 = M1_814;
        this.M1_815 = M1_815;
        this.M1_lik1 = M1_lik1;
        this.M1_lik2 = M1_lik2;
        this.M1_lik3 = M1_lik3;
        this.M1_lik4 = M1_lik4;
        this.M1_lik5 = M1_lik5;
        this.M1_lik1B = M1_lik1B;
        this.M1_lik2B = M1_lik2B;
        this.M1_lik3B = M1_lik3B;
        this.M1_lik4B = M1_lik4B;
        this.M1_lik5B = M1_lik5B;
    }

    @NotNull
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(@NotNull String status) {
        this.status = status;
    }

    @NotNull
    public String getRequest_type() {
        return request_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRequest_type(@NotNull String request_type) {
        this.request_type = request_type;
    }

    @NotNull
    public String getFk_id() {
        return fk_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_id(@NotNull String fk_id) {
        this.fk_id = fk_id;
    }

    @NotNull
    public String getUID() {
        return UID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUID(@NotNull String UID) {
        this.UID = UID;
    }

    @NotNull
    public String getM1_created_at() {
        return M1_created_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_created_at(@NotNull String M1_created_at) {
        this.M1_created_at = M1_created_at;
    }

    @NotNull
    public String getM1_updated_at() {
        return M1_updated_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_updated_at(@NotNull String M1_updated_at) {
        this.M1_updated_at = M1_updated_at;
    }

    @NotNull
    public String getM1_nama() {
        return M1_nama;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_nama(@NotNull String M1_nama) {
        this.M1_nama = M1_nama;
    }

    @NotNull
    public String getM1_101() {
        return M1_101;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_101(@NotNull String M1_101) {
        this.M1_101 = M1_101;
    }

    @NotNull
    public String getM1_102() {
        return M1_102;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_102(@NotNull String M1_102) {
        this.M1_102 = M1_102;
    }

    @NotNull
    public String getM1_103() {
        return M1_103;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_103(@NotNull String M1_103) {
        this.M1_103 = M1_103;
    }

    @NotNull
    public String getM1_104() {
        return M1_104;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_104(@NotNull String M1_104) {
        this.M1_104 = M1_104;
    }

    @NotNull
    public String getM1_105() {
        return M1_105;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_105(@NotNull String M1_105) {
        this.M1_105 = M1_105;
    }

    @NotNull
    public String getM1_106() {
        return M1_106;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_106(@NotNull String M1_106) {
        this.M1_106 = M1_106;
    }

    @NotNull
    public String getM1_107() {
        return M1_107;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_107(@NotNull String M1_107) {
        this.M1_107 = M1_107;
    }

    @NotNull
    public String getM1_108() {
        return M1_108;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_108(@NotNull String M1_108) {
        this.M1_108 = M1_108;
    }

    @NotNull
    public String getM1_109() {
        return M1_109;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_109(@NotNull String M1_109) {
        this.M1_109 = M1_109;
    }

    @NotNull
    public String getM1_110() {
        return M1_110;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_110(@NotNull String M1_110) {
        this.M1_110 = M1_110;
    }

    @NotNull
    public String getM1_401() {
        return M1_401;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_401(@NotNull String M1_401) {
        this.M1_401 = M1_401;
    }

    @NotNull
    public String getM1_402() {
        return M1_402;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_402(@NotNull String M1_402) {
        this.M1_402 = M1_402;
    }

    @NotNull
    public String getM1_403() {
        return M1_403;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_403(@NotNull String M1_403) {
        this.M1_403 = M1_403;
    }

    @NotNull
    public String getM1_404() {
        return M1_404;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_404(@NotNull String M1_404) {
        this.M1_404 = M1_404;
    }

    @NotNull
    public String getM1_405() {
        return M1_405;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_405(@NotNull String M1_405) {
        this.M1_405 = M1_405;
    }

    @NotNull
    public String getM1_406() {
        return M1_406;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_406(@NotNull String M1_406) {
        this.M1_406 = M1_406;
    }

    @NotNull
    public String getM1_407() {
        return M1_407;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_407(@NotNull String M1_407) {
        this.M1_407 = M1_407;
    }

    @NotNull
    public String getM1_501() {
        return M1_501;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_501(@NotNull String M1_501) {
        this.M1_501 = M1_501;
    }

    @NotNull
    public String getM1_502() {
        return M1_502;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_502(@NotNull String M1_502) {
        this.M1_502 = M1_502;
    }

    @NotNull
    public String getM1_503() {
        return M1_503;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_503(@NotNull String M1_503) {
        this.M1_503 = M1_503;
    }

    @NotNull
    public String getM1_504() {
        return M1_504;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_504(@NotNull String M1_504) {
        this.M1_504 = M1_504;
    }

    @NotNull
    public String getM1_505() {
        return M1_505;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_505(@NotNull String M1_505) {
        this.M1_505 = M1_505;
    }

    @NotNull
    public String getM1_506() {
        return M1_506;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_506(@NotNull String M1_506) {
        this.M1_506 = M1_506;
    }

    @NotNull
    public String getM1_507() {
        return M1_507;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_507(@NotNull String M1_507) {
        this.M1_507 = M1_507;
    }

    @NotNull
    public String getM1_508() {
        return M1_508;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_508(@NotNull String M1_508) {
        this.M1_508 = M1_508;
    }

    @NotNull
    public String getM1_509() {
        return M1_509;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_509(@NotNull String M1_509) {
        this.M1_509 = M1_509;
    }

    @NotNull
    public String getM1_510() {
        return M1_510;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_510(@NotNull String M1_510) {
        this.M1_510 = M1_510;
    }

    @NotNull
    public String getM1_601() {
        return M1_601;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_601(@NotNull String M1_601) {
        this.M1_601 = M1_601;
    }

    @NotNull
    public String getM1_601_kode() {
        return M1_601_kode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_601_kode(@NotNull String M1_601_kode) {
        this.M1_601_kode = M1_601_kode;
    }

    @NotNull
    public String getM1_602_kode() {
        return M1_602_kode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_602_kode(@NotNull String M1_602_kode) {
        this.M1_602_kode = M1_602_kode;
    }

    @NotNull
    public String getM1_603_kode() {
        return M1_603_kode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_603_kode(@NotNull String M1_603_kode) {
        this.M1_603_kode = M1_603_kode;
    }

    @NotNull
    public String getM1_602() {
        return M1_602;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_602(@NotNull String M1_602) {
        this.M1_602 = M1_602;
    }

    @NotNull
    public String getM1_603() {
        return M1_603;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_603(@NotNull String M1_603) {
        this.M1_603 = M1_603;
    }

    @NotNull
    public String getM1_604() {
        return M1_604;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_604(@NotNull String M1_604) {
        this.M1_604 = M1_604;
    }

    @NotNull
    public String getM1_605() {
        return M1_605;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_605(@NotNull String M1_605) {
        this.M1_605 = M1_605;
    }

    @NotNull
    public String getM1_606() {
        return M1_606;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_606(@NotNull String M1_606) {
        this.M1_606 = M1_606;
    }

    @NotNull
    public String getM1_607() {
        return M1_607;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_607(@NotNull String M1_607) {
        this.M1_607 = M1_607;
    }

    @NotNull
    public String getM1_608() {
        return M1_608;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_608(@NotNull String M1_608) {
        this.M1_608 = M1_608;
    }

    @NotNull
    public String getM1_609() {
        return M1_609;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_609(@NotNull String M1_609) {
        this.M1_609 = M1_609;
    }

    @NotNull
    public String getM1_610() {
        return M1_610;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_610(@NotNull String M1_610) {
        this.M1_610 = M1_610;
    }

    @NotNull
    public String getM1_611() {
        return M1_611;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_611(@NotNull String M1_611) {
        this.M1_611 = M1_611;
    }

    @NotNull
    public String getM1_612() {
        return M1_612;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_612(@NotNull String M1_612) {
        this.M1_612 = M1_612;
    }

    @NotNull
    public String getM1_613() {
        return M1_613;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_613(@NotNull String M1_613) {
        this.M1_613 = M1_613;
    }

    @NotNull
    public String getM1_614() {
        return M1_614;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_614(@NotNull String M1_614) {
        this.M1_614 = M1_614;
    }

    @NotNull
    public String getM1_615() {
        return M1_615;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_615(@NotNull String M1_615) {
        this.M1_615 = M1_615;
    }

    @NotNull
    public String getM1_616() {
        return M1_616;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_616(@NotNull String M1_616) {
        this.M1_616 = M1_616;
    }

    @NotNull
    public String getM1_617() {
        return M1_617;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_617(@NotNull String M1_617) {
        this.M1_617 = M1_617;
    }

    @NotNull
    public String getM1_618() {
        return M1_618;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_618(@NotNull String M1_618) {
        this.M1_618 = M1_618;
    }

    @NotNull
    public String getM1_701() {
        return M1_701;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_701(@NotNull String M1_701) {
        this.M1_701 = M1_701;
    }

    @NotNull
    public String getM1_702() {
        return M1_702;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_702(@NotNull String M1_702) {
        this.M1_702 = M1_702;
    }

    @NotNull
    public String getM1_703() {
        return M1_703;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_703(@NotNull String M1_703) {
        this.M1_703 = M1_703;
    }

    @NotNull
    public String getM1_801() {
        return M1_801;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_801(@NotNull String M1_801) {
        this.M1_801 = M1_801;
    }

    @NotNull
    public String getM1_802() {
        return M1_802;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_802(@NotNull String M1_802) {
        this.M1_802 = M1_802;
    }

    @NotNull
    public String getM1_803() {
        return M1_803;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_803(@NotNull String M1_803) {
        this.M1_803 = M1_803;
    }

    @NotNull
    public String getM1_804() {
        return M1_804;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_804(@NotNull String M1_804) {
        this.M1_804 = M1_804;
    }

    @NotNull
    public String getM1_805() {
        return M1_805;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_805(@NotNull String M1_805) {
        this.M1_805 = M1_805;
    }

    @NotNull
    public String getM1_806() {
        return M1_806;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_806(@NotNull String M1_806) {
        this.M1_806 = M1_806;
    }

    @NotNull
    public String getM1_807() {
        return M1_807;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_807(@NotNull String M1_807) {
        this.M1_807 = M1_807;
    }

    @NotNull
    public String getM1_808() {
        return M1_808;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_808(@NotNull String M1_808) {
        this.M1_808 = M1_808;
    }

    @NotNull
    public String getM1_809() {
        return M1_809;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_809(@NotNull String M1_809) {
        this.M1_809 = M1_809;
    }

    @NotNull
    public String getM1_810() {
        return M1_810;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_810(@NotNull String M1_810) {
        this.M1_810 = M1_810;
    }

    @NotNull
    public String getM1_811() {
        return M1_811;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_811(@NotNull String M1_811) {
        this.M1_811 = M1_811;
    }

    @NotNull
    public String getM1_812() {
        return M1_812;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_812(@NotNull String M1_812) {
        this.M1_812 = M1_812;
    }

    @NotNull
    public String getM1_813() {
        return M1_813;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_813(@NotNull String M1_813) {
        this.M1_813 = M1_813;
    }

    @NotNull
    public String getM1_814() {
        return M1_814;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_814(@NotNull String M1_814) {
        this.M1_814 = M1_814;
    }

    @NotNull
    public String getM1_815() {
        return M1_815;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_815(@NotNull String M1_815) {
        this.M1_815 = M1_815;
    }

    @NotNull
    public String getM1_lik1() {
        return M1_lik1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik1(@NotNull String M1_lik1) {
        this.M1_lik1 = M1_lik1;
    }

    @NotNull
    public String getM1_lik2() {
        return M1_lik2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik2(@NotNull String M1_lik2) {
        this.M1_lik2 = M1_lik2;
    }

    @NotNull
    public String getM1_lik3() {
        return M1_lik3;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik3(@NotNull String M1_lik3) {
        this.M1_lik3 = M1_lik3;
    }

    @NotNull
    public String getM1_lik4() {
        return M1_lik4;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik4(@NotNull String M1_lik4) {
        this.M1_lik4 = M1_lik4;
    }

    @NotNull
    public String getM1_lik5() {
        return M1_lik5;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik5(@NotNull String M1_lik5) {
        this.M1_lik5 = M1_lik5;
    }

    @NotNull
    public String getM1_lik1B() {
        return M1_lik1B;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik1B(@NotNull String M1_lik1B) {
        this.M1_lik1B = M1_lik1B;
    }

    @NotNull
    public String getM1_lik2B() {
        return M1_lik2B;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik2B(@NotNull String M1_lik2B) {
        this.M1_lik2B = M1_lik2B;
    }

    @NotNull
    public String getM1_lik3B() {
        return M1_lik3B;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik3B(@NotNull String M1_lik3B) {
        this.M1_lik3B = M1_lik3B;
    }

    @NotNull
    public String getM1_lik4B() {
        return M1_lik4B;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik4B(@NotNull String M1_lik4B) {
        this.M1_lik4B = M1_lik4B;
    }

    @NotNull
    public String getM1_lik5B() {
        return M1_lik5B;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setM1_lik5B(@NotNull String M1_lik5B) {
        this.M1_lik5B = M1_lik5B;
    }

}
