package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "KELUARGA_QUEUE".
 */
@Entity
public class KeluargaQueue {

    @NotNull
    private String fki_id;

    @NotNull
    private String fki_fk_id;

    @NotNull
    private String fk_202_nama;

    @NotNull
    private String fk_202_nik;

    @NotNull
    private String fk_203;

    @NotNull
    private String fk_204;

    @NotNull
    private String fk_205;

    @NotNull
    private String fk_206;

    @NotNull
    private String fk_207;

    @NotNull
    private String fk_208;

    @NotNull
    private String fk_209;

    @NotNull
    private String fk_210;

    @NotNull
    private String fk_303;

    @NotNull
    private String fk_304;

    @NotNull
    private String fk_305;

    @NotNull
    private String fk_306;

    @NotNull
    private String fk_307;

    @NotNull
    private String fk_308;

    @Generated(hash = 1097792210)
    public KeluargaQueue() {
    }

    @Generated(hash = 1505799298)
    public KeluargaQueue(@NotNull String fki_id, @NotNull String fki_fk_id, @NotNull String fk_202_nama, @NotNull String fk_202_nik, @NotNull String fk_203, @NotNull String fk_204, @NotNull String fk_205, @NotNull String fk_206, @NotNull String fk_207, @NotNull String fk_208, @NotNull String fk_209,
            @NotNull String fk_210, @NotNull String fk_303, @NotNull String fk_304, @NotNull String fk_305, @NotNull String fk_306, @NotNull String fk_307, @NotNull String fk_308) {
        this.fki_id = fki_id;
        this.fki_fk_id = fki_fk_id;
        this.fk_202_nama = fk_202_nama;
        this.fk_202_nik = fk_202_nik;
        this.fk_203 = fk_203;
        this.fk_204 = fk_204;
        this.fk_205 = fk_205;
        this.fk_206 = fk_206;
        this.fk_207 = fk_207;
        this.fk_208 = fk_208;
        this.fk_209 = fk_209;
        this.fk_210 = fk_210;
        this.fk_303 = fk_303;
        this.fk_304 = fk_304;
        this.fk_305 = fk_305;
        this.fk_306 = fk_306;
        this.fk_307 = fk_307;
        this.fk_308 = fk_308;
    }

    @NotNull
    public String getFki_id() {
        return fki_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFki_id(@NotNull String fki_id) {
        this.fki_id = fki_id;
    }

    @NotNull
    public String getFki_fk_id() {
        return fki_fk_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFki_fk_id(@NotNull String fki_fk_id) {
        this.fki_fk_id = fki_fk_id;
    }

    @NotNull
    public String getFk_202_nama() {
        return fk_202_nama;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_202_nama(@NotNull String fk_202_nama) {
        this.fk_202_nama = fk_202_nama;
    }

    @NotNull
    public String getFk_202_nik() {
        return fk_202_nik;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_202_nik(@NotNull String fk_202_nik) {
        this.fk_202_nik = fk_202_nik;
    }

    @NotNull
    public String getFk_203() {
        return fk_203;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_203(@NotNull String fk_203) {
        this.fk_203 = fk_203;
    }

    @NotNull
    public String getFk_204() {
        return fk_204;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_204(@NotNull String fk_204) {
        this.fk_204 = fk_204;
    }

    @NotNull
    public String getFk_205() {
        return fk_205;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_205(@NotNull String fk_205) {
        this.fk_205 = fk_205;
    }

    @NotNull
    public String getFk_206() {
        return fk_206;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_206(@NotNull String fk_206) {
        this.fk_206 = fk_206;
    }

    @NotNull
    public String getFk_207() {
        return fk_207;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_207(@NotNull String fk_207) {
        this.fk_207 = fk_207;
    }

    @NotNull
    public String getFk_208() {
        return fk_208;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_208(@NotNull String fk_208) {
        this.fk_208 = fk_208;
    }

    @NotNull
    public String getFk_209() {
        return fk_209;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_209(@NotNull String fk_209) {
        this.fk_209 = fk_209;
    }

    @NotNull
    public String getFk_210() {
        return fk_210;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_210(@NotNull String fk_210) {
        this.fk_210 = fk_210;
    }

    @NotNull
    public String getFk_303() {
        return fk_303;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_303(@NotNull String fk_303) {
        this.fk_303 = fk_303;
    }

    @NotNull
    public String getFk_304() {
        return fk_304;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_304(@NotNull String fk_304) {
        this.fk_304 = fk_304;
    }

    @NotNull
    public String getFk_305() {
        return fk_305;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_305(@NotNull String fk_305) {
        this.fk_305 = fk_305;
    }

    @NotNull
    public String getFk_306() {
        return fk_306;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_306(@NotNull String fk_306) {
        this.fk_306 = fk_306;
    }

    @NotNull
    public String getFk_307() {
        return fk_307;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_307(@NotNull String fk_307) {
        this.fk_307 = fk_307;
    }

    @NotNull
    public String getFk_308() {
        return fk_308;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFk_308(@NotNull String fk_308) {
        this.fk_308 = fk_308;
    }

}
