package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PETUGAS".
 */
@Entity
public class Petugas {

    @NotNull
    private String u_id;

    @NotNull
    private String u_username;

    @NotNull
    private String u_name;

    @NotNull
    private String u_email;

    @NotNull
    private String u_phone;

    @NotNull
    private String u_rule;

    @NotNull
    private String u_status;

    @Generated(hash = 607626037)
    public Petugas() {
    }

    @Generated(hash = 498627920)
    public Petugas(@NotNull String u_id, @NotNull String u_username, @NotNull String u_name, @NotNull String u_email,
            @NotNull String u_phone, @NotNull String u_rule, @NotNull String u_status) {
        this.u_id = u_id;
        this.u_username = u_username;
        this.u_name = u_name;
        this.u_email = u_email;
        this.u_phone = u_phone;
        this.u_rule = u_rule;
        this.u_status = u_status;
    }

    @NotNull
    public String getU_id() {
        return u_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_id(@NotNull String u_id) {
        this.u_id = u_id;
    }

    @NotNull
    public String getU_username() {
        return u_username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_username(@NotNull String u_username) {
        this.u_username = u_username;
    }

    @NotNull
    public String getU_name() {
        return u_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_name(@NotNull String u_name) {
        this.u_name = u_name;
    }

    @NotNull
    public String getU_email() {
        return u_email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_email(@NotNull String u_email) {
        this.u_email = u_email;
    }

    @NotNull
    public String getU_phone() {
        return u_phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_phone(@NotNull String u_phone) {
        this.u_phone = u_phone;
    }

    @NotNull
    public String getU_rule() {
        return u_rule;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_rule(@NotNull String u_rule) {
        this.u_rule = u_rule;
    }

    @NotNull
    public String getU_status() {
        return u_status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setU_status(@NotNull String u_status) {
        this.u_status = u_status;
    }

}
