package com.karyastudio.izn.dao.generateSchema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PROVINSI".
 */
@Entity
public class Provinsi {

    @NotNull
    private String pro_id;

    @NotNull
    private String pro_code;

    @NotNull
    private String pro_province;

    @Generated(hash = 12525008)
    public Provinsi() {
    }

    @Generated(hash = 192507089)
    public Provinsi(@NotNull String pro_id, @NotNull String pro_code, @NotNull String pro_province) {
        this.pro_id = pro_id;
        this.pro_code = pro_code;
        this.pro_province = pro_province;
    }

    @NotNull
    public String getPro_id() {
        return pro_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_id(@NotNull String pro_id) {
        this.pro_id = pro_id;
    }

    @NotNull
    public String getPro_code() {
        return pro_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_code(@NotNull String pro_code) {
        this.pro_code = pro_code;
    }

    @NotNull
    public String getPro_province() {
        return pro_province;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro_province(@NotNull String pro_province) {
        this.pro_province = pro_province;
    }

}
